version: '3'
services:
  node:
    build: ./backend
    container_name: backend
    restart: always
    volumes:
      - ./backend/:/volumes
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: database
      MYSQL_PORT: 3306
    depends_on:
      - "database"

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventoryinc
    ports:
      - "3306:3306"